--bookmarks
drop table if exists bookmarks;

create table bookmarks(
    id INTEGER primary key generated by default as identity,
    title text NOT NULL,
    url text NOT NULL,
    rating INTEGER NOT NULL,
    description text);

insert into bookmarks (id, title, url, rating, description)
values
(1, 'Google', 'google.com', 5, 'a website for queries'),
(2, 'Thinkful', 'thinkful.com', 4, 'a webiste to learn');

